### ISSUE TITLE
Implement starkent_keccak

### ISSUE THREAD

**Issue by Sh0g0-1758** [BlocSoc-iitr/Athena#7]
Refer utils.py in starknet_abi and add tests as well.

**Comment by Rishikpulhani** [comment]
Pls assign

**Comment by Sh0g0-1758** [comment]
Hey @Rishikpulhani I ended up implementing it because I needed it for some other file. You can work on its tests in some other issue.

**Comment by Rishikpulhani** [comment]
Ok sir
